export PATH="$HOME/.cargo/bin:/opt/homebrew/bin:$PATH"

source $(brew --prefix)/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source /opt/homebrew/share/zsh-autosuggestions/zsh-autosuggestions.zsh

HISTFILE=$HOME/.zsh_history
SAVEHIST=1000
HISTSIZE=999
setopt share_history
setopt hist_expire_dups_first
setopt hist_ignore_dups
setopt hist_verify

bindkey '^[[A' history-search-backward
bindkey '^[[B' history-search-forward


alias ls="eza --icons=always"
alias ll="ls -lh"

eval "$(zoxide init zsh)"
alias cd="z"

eval "$(starship init zsh)"
