unbind C-b
set -g prefix C-f
bind C-f send-prefix

set-option -g default-shell /opt/homebrew/bin/fish
set-environment -g PATH "/usr/local/bin:/bin:/usr/bin:/opt/homebrew/bin"

bind-key v split-window -h -l 100 -c '#{pane_current_path}'
bind-key s split-window -v -l 30 -c '#{pane_current_path}'

set -g renumber-windows on

set -g base-index 1
setw -g pane-base-index 1

bind-key j select-pane -D 
bind-key k select-pane -U 
bind-key h select-pane -L 
bind-key l select-pane -R


bind-key x kill-pane

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'arcticicestudio/nord-tmux'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
source ~/.tmuxline

